# Generated by Django 5.1.7 on 2025-03-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('background', models.CharField(max_length=8)),
                ('foreground', models.CharField(max_length=8)),
                ('cursor_background', models.CharField(max_length=8)),
                ('cursor_foreground', models.CharField(max_length=8)),
                ('color0', models.CharField(max_length=8)),
                ('color1', models.CharField(max_length=8)),
                ('color2', models.CharField(max_length=8)),
                ('color3', models.CharField(max_length=8)),
                ('color4', models.CharField(max_length=8)),
                ('color5', models.CharField(max_length=8)),
                ('color6', models.CharField(max_length=8)),
                ('color7', models.CharField(max_length=8)),
                ('color8', models.CharField(max_length=8)),
                ('color9', models.CharField(max_length=8)),
                ('color10', models.CharField(max_length=8)),
                ('color11', models.CharField(max_length=8)),
                ('color12', models.CharField(max_length=8)),
                ('color13', models.CharField(max_length=8)),
                ('color14', models.CharField(max_length=8)),
                ('color15', models.CharField(max_length=8)),
                ('contrast_ratio', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
