# Generated by Django 5.1.7 on 2025-03-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorscheme',
            name='id',
        ),
        migrations.AlterField(
            model_name='colorscheme',
            name='path',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
